export const FULL_DATA_LOAD = 'FULL_DATA_LOAD';

export const COMPANY_DATA_LOAD = 'COMPANY_DATA_LOAD';
export const COMPANY_SINGLE_LOAD = 'COMPANY_SINGLE_LOAD';

export const CURRENCY_DATA_LOAD = 'CURRENCY_DATA_LOAD';
export const CURRENCY_SINGLE_LOAD = 'CURRENCY_SINGLE_LOAD';